#!/usr/bin/env python3

import subprocess
import argparse
import sys
import glob
import regex as re

# TODO
# ----
# - compile regex expressions

def get_end(xreflines , allfiles , file , lno):
    """
    Finds end of subroutine, function or programm for a given 
    line of code.

    Arguments:
        xreflines (list) : Mostly output from ctags in the form
                           [
                             {
                               "tag" : <name of variable, function, ...> , 
                               "type" : <"subroutine", "label", ...> , 
                               "line" : <integer with the line number> , 
                               "file" : <path to the file> , 
                               "expression" : <full code expression>
                             } , ...
                           ]
        allfiles (dict) : Contains the files with the code in the form
                           {<filename> : <string with the file contents>}   
        file (str) : File path
        lno (int) : Line number

    Returns:
        TODO
    """
    possible = [
            entry["line"] for entry in xreflines if 
                entry["line"] >= lno and 
                entry["type"] in ["subroutine" , "function" , "program"] and
                entry["file"] == file]
    possible.append(len(allfiles[file]))
    end = min(possible)
    return (file , end , allfiles[file][lno - 1 : end - 1 + 1])

def get_start(xreflines , allfiles , file , lno):
    """
    Finds start of subroutine, function or programm for a given 
    line of code.

    Arguments:
        xreflines (list) : Mostly output from ctags in the form
                           [
                             {
                               "tag" : <name of variable, function, ...> , 
                               "type" : <"subroutine", "label", ...> , 
                               "line" : <integer with the line number> , 
                               "file" : <path to the file> , 
                               "expression" : <full code expression>
                             } , ...
                           ]
        allfiles (dict) : Contains the files with the code in the form
                           {<filename> : <string with the file contents>}   
        file (str) : File path
        lno (int) : Line number
    Returns:
        TODO
    """
    possible = [
            entry["line"] for entry in xreflines if 
                entry["line"] <= lno and 
                entry["type"] in ["subroutine" , "function" , "program"] and
                entry["file"] == file]
    possible.append(1)
    start = max(possible)
    return (file , start , allfiles[file][start - 1 : lno - 1])

# parsing arguments
# -----------------

parser = argparse.ArgumentParser(description = 
"""
Check fixed fortran files for changes in the values in common blocks. 
CAREFULL this is not perfect, some value changes may be missed.
""")
parser.add_argument("--tags" , "-t" , 
                    help = "Common block name, if not specified all common blocks will be used." , 
                    action = "append" , 
                    default = [])
parser.add_argument("--file" , "-f" , 
                    help = "Path to file for use with ctags, if no files specified *.f will be used. Note all files must be fixed form." , 
                    action = "append" , 
                    default = [])
args = parser.parse_args()

# getting files
# -------------

files = args.file
if len(args.file) == 0:
    files = glob.glob('*.f')
allfiles = dict()
for f in files:
    with open(f , "r") as fle:
        allfiles[f] = fle.readlines()
command = ["ctags" , "--output-format=xref" , "-n"] + files

# getting data from ctags
# -----------------------
# - each line of the ctags output is turned into a dictionary

xref = subprocess.run(command , capture_output = True , text = True)

xreflines = \
        list(map(lambda x : 
                 dict(
                     zip(
                        ["tag" , "type" , "line" , "file" , "expression"] , 
                        x.split(maxsplit = 4))) ,
                 xref.stdout.splitlines()))

# fixing entries
# ----------------------------------------------------
# - strings to int
# - the last element generated by `ctags` is the code line,
#   unfortunately it might not contain the entire expression
#   if there was a line break
# - ctags seems to ignore some variables, making list of tags
#   for each expression

alltags = dict()
for x in xreflines:
    if x["tag"].lower() in alltags:
        if not x["type"].lower() in alltags[x["tag"].lower()]:
            alltags[x["tag"].lower()].append(x["type"].strip())
    else:
        alltags[x["tag"].lower()] = [x["type"].lower()]

for entry in xreflines:
    entry["tag"] = entry["tag"].lower()
    entry["type"] = entry["type"].lower()
    entry["line"] = int(entry["line"])
    expression = ""
    with open(entry["file"] , "r") as f:
        lne = entry["line"] - 1
        while True:
            line = allfiles[entry["file"]][lne]
            if line[0].lower() != "c":
                if "!" in line:
                    pos = line.find("!")
                    line = line[:pos]
                expression += line 
            lne += 1
            if lne >= len(allfiles[entry["file"]]):
                break
            if allfiles[entry["file"]][0] != "&":
                break
            if allfiles[entry["file"]].strip() == "":
                break
    entry["expression"] = expression
    entry["expression_tags"] = \
            list(
                filter(
                    lambda s : len(s) > 0 and (re.match(r"[a-z]+?" , s) is not None), 
                    map(
                        lambda x : x.strip() , 
                        re.split(r"[\(\),/\s\b^$]" , expression.lower()))))

# checking common
# ---------------
# - checking if values from the common are
#   modified or initialized in function, subroutine, program

args.tags = [x.lower() for x in args.tags]
if len(args.tags) == 0:
    s = set()
    for entry in xreflines:
        if entry["type"] == "common":
            s.add(entry["tag"].lower())
    args.tags = list(s)
    args.tags.sort()

for tagg in args.tags:
    print("CHECKING : " , tagg.lower())
    istagmodified = False
    for entry in xreflines:
        if entry["tag"] == tagg.lower() and entry["type"] == "common":
            file , end , code = get_end(xreflines , allfiles , entry["file"] , entry["line"])
            file_s , start , code_s = get_start(xreflines , allfiles , entry["file"] , entry["line"])
            print("  FOUND IN" , code_s[0].strip().lower())
            print("    FILE" , entry["file"])
            print("    LINE" , entry["line"])
            codenocomments = [line.lower() for line in code if (line.lower()[0] != "c" or line.lower()[0] != "!")]
            codenocomments = [line[:line.find("!")] if "!" in line else line for line in codenocomments]
            code = "\n" + "".join(codenocomments).lower() + "\n"
            modified = 0
            for tag in entry["expression_tags"]:
                # sauce : https://dnmtechs.com/exploring-recursive-patterns-in-regex-with-python-3/
                allcalls = re.findall(r"([a-z0-9]+?)(\((?:[^()]+|(?R))*\))" , code)
                incallset = set()
                for f , a in allcalls:
                    if f.strip() in alltags:
                        typestag = alltags[f.strip()]
                        if "function" in typestag or "subroutine" in typestag:
                            tagina = re.findall(r"(" + tag + r"\((?:[^()]+|(?R))*\))" , a)
                            tagina += re.findall(r"(\b" + tag + r"\b)" , a)
                            for el in tagina:
                                incallset.add("      " + (f + a).strip() + "\n")
                incalllist = list(incallset)
                incalllist.sort()
                if len(incalllist) > 0:
                    print("    IN CALL" , tag , ":")
                    istagmodified = True
                    modified = 1
                for el in incalllist:
                    sys.stdout.write(el)
                #isset = re.findall(r"[^a-z0-9]" + tag + r"\s*?=|[^a-z0-9]" + tag + r"\s*?\([a-z0-9,]+?\)\s*?=" , code) 
                isset = re.findall(r"(" + tag + r"\((?:[^()]+|(?R))*\)\s*?=)" , code)
                isset += re.findall(r"(" + tag + r"\s*?=)" , code)
                issetset = set()
                if len(isset) != 0:
                    modified = 2
                    istagmodified = True
                    print("    CHANGED OR INITIALIZED" , tag , ":")
                    for s in isset:
                        issetset.add("      " + s.strip() + "\n")
                issetlist = list(issetset)
                issetlist.sort()
                for el in issetlist:
                    sys.stdout.write(el)
                #print("    " , isincall)
            if modified == 2:
                print("    !!!MODIFIED!!!")
                istagmodified = True
            elif modified == 1:
                print("    !!!POSSIBLY MODIFIED!!!")
    if istagmodified:
        pass
    else:
        print("  !!!COULD NOT FIND MODIFICATIONS OR INITIALIZATION!!!")

